spring.application.name=video-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.port=8082

aws.access-key=${AWS_ACCESS_KEY:AKIA564PXR4SRHN7QO6D}
aws.secret-key=${AWS_SECRET_KEY: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}
aws.region=${AWS_REGION:eu-north-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:netflix-steaming-videos-959689756453-eu-north-1-an}

management.endpoints.web.exposure.include=health,info