spring.application.name=encoding-service

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=encoding-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.netflix.encodingservice.event.VideoUploadedEvent

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Server
server.port=8083

# AWS Configuration
aws.access-key=${AWS_ACCESS_KEY:AKIA564PXR4SRHN7QO6D}
aws.secret-key=${AWS_SECRET_KEY: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}
aws.region=${AWS_REGION:eu-north-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:netflix-steaming-videos-959689756453-eu-north-1-an}

# FFmpeg Configuration
ffmpeg.path=C:/Users/VARUN SINGH/Downloads/ffmpeg-8.1.2-essentials_build/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe
# Temp Directory
encoding.temp-dir=${TEMP_DIR:C:/temp/encoding}

# Actuator
management.endpoints.web.exposure.include=health,info